### ISSUE TITLE
Automated bug report: password_dialog() got multiple values for argument 'msg'

### ISSUE THREAD

**Issue by SCZaphoid** [SmartCash/electrum-smart#7]
## Description

Starting nodes on Windows 10, OS X Mojave, and Ubuntu 18 have the same result.

## Stack
```
  File "site-packages\electrum_smart-4.0.0-py3.5.egg\electrum_smart_gui\qt\smartnode_tab.py", line 480, in start_current_smartnode
  File "site-packages\electrum_smart-4.0.0-py3.5.egg\electrum_smart_gui\qt\smartnode_tab.py", line 489, in sign_announce

```
## Environment

 - file: site-packages\electrum_smart-4.0.0-py3.5.egg\electrum_smart_gui\qt\smartnode_tab.py
 - name: sign_announce
 - type: TypeError

## Additional information

 - app_version: 4.0.0
 - os: Windows-10-10.0.17134-SP0
 - wallet_type: standard
 - locale: en_US

**Comment by SCZaphoid** [comment]
```
Traceback (most recent call last):
  File "site-packages\electrum_smart-4.0.0-py3.5.egg\electrum_smart_gui\qt\smartnode_tab.py", line 480, in start_current_smartnode
  File "site-packages\electrum_smart-4.0.0-py3.5.egg\electrum_smart_gui\qt\smartnode_tab.py", line 489, in sign_announce
TypeError: password_dialog() got multiple values for argument 'msg'
```

**Comment by rc125** [comment]
Fixed in https://github.com/SmartCash/electrum-smart/commit/a1307861a2058eb8572476c2d7fc2cacfb9dc787
